language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

services:
  - docker

branches:
  only:
    - develop

before_install:
  - docker pull jekyll/minimal:3.5.1

install:
  - docker run --volume="$PWD:/srv/jekyll" jekyll/minimal:3.5.1 jekyll build

script:
  - npx gh-pages -x -b master -d _site -r https://${GITHUB_ACCESS_TOKEN}@github.com/MwumLi/MwumLi.github.io.git

