language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

services:
  - docker

branches:
  only:
    - develop

before_install:
  - docker pull jekyll/minimal:3.5.1

install:
  - docker run --volume="$PWD:/srv/jekyll" jekyll/minimal:3.5.1 jekyll build

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site
  target_branch: master
  on:
    branch: develop
